server:
  port: 9001
  shutdown: graceful
  servlet:
    context-path: /api
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-service
  output:
    ansi:
      enabled: always
  cloud:
    config:
      enabled: false
  profiles:
    active: develop
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/inditex_db
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  system: Inditex Ecommerce Application

management:
  endpoints:
    web:
      exposure:
        include: configprops, env, flyway, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}