global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'catalog-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'catalog-service:9001' ]
  
